services:
  sudomake-friends:
    container_name: sudomake-friends
    build:
      context: .
      args:
        APP_UID: ${DOCKER_UID:-1000}
        APP_GID: ${DOCKER_GID:-1000}
    env_file:
      - .env
      - ~/.sudomake-friends/.env
    environment:
      - DATA_DIR=/app/data
    restart: unless-stopped
    volumes:
      - ~/.sudomake-friends/data:/app/data
      - ~/.sudomake-friends/friends:/app/friends:ro
